name: Docker Compose Deploy

on:
  push:
    branches:
      - main  # Cambiar por el nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo rm /usr/local/bin/docker-compose  # Eliminar versión anterior, si existe
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose  # Descargar Docker Compose 1.29.2
          sudo chmod +x /usr/local/bin/docker-compose  # Dar permisos de ejecución a Docker Compose

      - name: Loguearse en GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io  # Cambiar si usas otro registro como Docker Hub (docker.io)
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build y levantar servicios con Docker Compose
        run: |
          docker-compose up -d --build
        working-directory: ./  # La raíz del repositorio donde está tu docker-compose.yml
