name: Docker Compose Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4.1.7


      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.3.0
        
      - name: Set up Docker Compose
        run: |
          sudo rm /usr/local/bin/docker-compose  # Eliminar versión anterior, si existe
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose  # Descargar Docker Compose 1.29.2
          sudo chmod +x /usr/local/bin/docker-compose  # Dar permisos de ejecución a Docker Compose

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: milydemendoza
          password: Angel2610#

      - name: Build y levantar servicios con Docker Compose
        run: |
          docker-compose up -d --build
        working-directory: ./  # La raíz del repositorio donde está tu docker-compose.yml
